In [1]:
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Graf35\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df_raw = pd.read_csv('disasters_social_media.csv', encoding='latin-1')
df_raw.head(5)

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,keyword,location,text,tweetid,userid
0,778243823,True,golden,156,NaN,Relevant,1.0000,Relevant,NaN,NaN,Just happened a terrible car crash,1.0,NaN
1,778243824,True,golden,152,NaN,Relevant,1.0000,Relevant,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,13.0,NaN
2,778243825,True,golden,137,NaN,Relevant,1.0000,Relevant,NaN,NaN,"Heard about #earthquake is different cities, s...",14.0,NaN
3,778243826,True,golden,136,NaN,Relevant,0.9603,Relevant,NaN,NaN,"there is a forest fire at spot pond, geese are...",15.0,NaN
4,778243827,True,golden,138,NaN,Relevant,1.0000,Relevant,NaN,NaN,Forest fire near La Ronge Sask. Canada,16.0,NaN

In [4]:
df_raw.tail()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,keyword,location,text,tweetid,userid
10871,778261105,True,golden,100,NaN,Relevant,0.7629,Relevant,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,5675678.0,NaN
10872,778261106,True,golden,90,NaN,Relevant,0.9203,Relevant,NaN,NaN,Police investigating after an e-bike collided ...,4234.0,NaN
10873,778261107,True,golden,102,NaN,Relevant,1.0000,Relevant,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,3242.0,NaN
10874,778261108,True,golden,96,NaN,Relevant,0.8419,Relevant,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...,457.0,NaN
10875,778261109,True,golden,97,NaN,Relevant,0.8812,Relevant,NaN,NaN,#CityofCalgary has activated its Municipal Eme...,6585.0,NaN

In [5]:
df_raw

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,keyword,location,text,tweetid,userid
0,778243823,True,golden,156,NaN,Relevant,1.0000,Relevant,NaN,NaN,Just happened a terrible car crash,1.0,NaN
1,778243824,True,golden,152,NaN,Relevant,1.0000,Relevant,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,13.0,NaN
2,778243825,True,golden,137,NaN,Relevant,1.0000,Relevant,NaN,NaN,"Heard about #earthquake is different cities, s...",14.0,NaN
3,778243826,True,golden,136,NaN,Relevant,0.9603,Relevant,NaN,NaN,"there is a forest fire at spot pond, geese are...",15.0,NaN
4,778243827,True,golden,138,NaN,Relevant,1.0000,Relevant,NaN,NaN,Forest fire near La Ronge Sask. Canada,16.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,778261105,True,golden,100,NaN,Relevant,0.7629,Relevant,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,5675678.0,NaN
10872,778261106,True,golden,90,NaN,Relevant,0.9203,Relevant,NaN,NaN,Police investigating after an e-bike collided ...,4234.0,NaN
10873,778261107,True,golden,102,NaN,Relevant,1.0000,Relevant,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,3242.0,NaN
10874,778261108,True,golden,96,NaN,Relevant,0.8419,Relevant,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...,457.0,NaN
10875,778261109,True,golden,97,NaN,Relevant,0.8812,Relevant,NaN,NaN,#CityofCalgary has activated its Municipal Eme...,6585.0,NaN

In [6]:
pd.read_csv('disasters_social_media.csv', nrows=1).columns.tolist()

['_unit_id',
 '_golden',
 '_unit_state',
 '_trusted_judgments',
 '_last_judgment_at',
 'choose_one',
 'choose_one:confidence',
 'choose_one_gold',
 'keyword',
 'location',
 'text',
 'tweetid',
 'userid']

In [7]:
df_raw.choose_one.values

array(['Relevant', 'Relevant', 'Relevant', ..., 'Relevant', 'Relevant',
       'Relevant'], dtype=object)

In [8]:
set(df_raw.choose_one.values)

{"Can't Decide", 'Not Relevant', 'Relevant'}

In [10]:
df = df_raw[df_raw.choose_one != "Can't Decide"]
df

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,choose_one,choose_one:confidence,choose_one_gold,keyword,location,text,tweetid,userid
0,778243823,True,golden,156,NaN,Relevant,1.0000,Relevant,NaN,NaN,Just happened a terrible car crash,1.0,NaN
1,778243824,True,golden,152,NaN,Relevant,1.0000,Relevant,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,13.0,NaN
2,778243825,True,golden,137,NaN,Relevant,1.0000,Relevant,NaN,NaN,"Heard about #earthquake is different cities, s...",14.0,NaN
3,778243826,True,golden,136,NaN,Relevant,0.9603,Relevant,NaN,NaN,"there is a forest fire at spot pond, geese are...",15.0,NaN
4,778243827,True,golden,138,NaN,Relevant,1.0000,Relevant,NaN,NaN,Forest fire near La Ronge Sask. Canada,16.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,778261105,True,golden,100,NaN,Relevant,0.7629,Relevant,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,5675678.0,NaN
10872,778261106,True,golden,90,NaN,Relevant,0.9203,Relevant,NaN,NaN,Police investigating after an e-bike collided ...,4234.0,NaN
10873,778261107,True,golden,102,NaN,Relevant,1.0000,Relevant,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,3242.0,NaN
10874,778261108,True,golden,96,NaN,Relevant,0.8419,Relevant,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...,457.0,NaN
10875,778261109,True,golden,97,NaN,Relevant,0.8812,Relevant,NaN,NaN,#CityofCalgary has activated its Municipal Eme...,6585.0,NaN

In [12]:
df = df[['text','choose_one']] # берем только столбцы 'text' и 'choose_one'
df

                                                    text choose_one
0                     Just happened a terrible car crash   Relevant
1      Our Deeds are the Reason of this #earthquake M...   Relevant
2      Heard about #earthquake is different cities, s...   Relevant
3      there is a forest fire at spot pond, geese are...   Relevant
4                 Forest fire near La Ronge Sask. Canada   Relevant
...                                                  ...        ...
10871  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...   Relevant
10872  Police investigating after an e-bike collided ...   Relevant
10873  The Latest: More Homes Razed by Northern Calif...   Relevant
10874  MEG issues Hazardous Weather Outlook (HWO) htt...   Relevant
10875  #CityofCalgary has activated its Municipal Eme...   Relevant

[10860 rows x 2 columns]

In [13]:
relevance = {'Relevant':1,'Not Relevant':0}
df['relevance'] = df.choose_one.map(relevance)
df

                                                    text choose_one  relevance
0                     Just happened a terrible car crash   Relevant          1
1      Our Deeds are the Reason of this #earthquake M...   Relevant          1
2      Heard about #earthquake is different cities, s...   Relevant          1
3      there is a forest fire at spot pond, geese are...   Relevant          1
4                 Forest fire near La Ronge Sask. Canada   Relevant          1
...                                                  ...        ...        ...
10871  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...   Relevant          1
10872  Police investigating after an e-bike collided ...   Relevant          1
10873  The Latest: More Homes Razed by Northern Calif...   Relevant          1
10874  MEG issues Hazardous Weather Outlook (HWO) htt...   Relevant          1
10875  #CityofCalgary has activated its Municipal Eme...   Relevant          1

[10860 rows x 3 columns]

In [15]:
def extract_words(sentence):
    ignore_words = stopwords.words()
    words = re.sub("[^\w]", " ", sentence).split() 
    words = [word.lower() for word in words]
    words_cleaned = [w.lower() for w in words if w not in ignore_words]
    return words_cleaned

In [16]:
def map_book(hash_map, tokens):
    if tokens is not None:
        for word in tokens:
            if word in hash_map:
                hash_map[word] = hash_map[word] + 1
            else:
                hash_map[word] = 1
        return hash_map
    else:
        return None

In [18]:
def make_hash_map(df):
    hash_map = {}
    for index, row in df.iterrows():
        hash_map = map_book(hash_map, extract_words(row['text']))
    return hash_map

In [19]:
def frequent_vocab(word_freq, max_features):
    counter = 0
    vocab = []
    for key, value in sorted(word_freq.items(), key=lambda item: (item[1], item[0]), reverse=True):
        if counter < max_features:
            vocab.append(key)
            counter+=1
        else: break
    return vocab

In [21]:
ash_map = make_hash_map(df)
vocab=frequent_vocab(ash_map, 500)
vocab

['co',
 'http',
 'https',
 'û_',
 'amp',
 'like',
 'fire',
 'get',
 'new',
 'via',
 '2',
 'news',
 'people',
 'emergency',
 'video',
 'disaster',
 'would',
 '3',
 'police',
 'still',
 'body',
 'suicide',
 'us',
 '1',
 'storm',
 'first',
 'time',
 'burning',
 'crash',
 'rt',
 'attack',
 'got',
 'back',
 'california',
 'day',
 'know',
 'fires',
 'two',
 'buildings',
 'going',
 'today',
 'see',
 'world',
 'nuclear',
 'bomb',
 'love',
 'hiroshima',
 'year',
 'full',
 'go',
 '5',
 'û',
 'dead',
 'youtube',
 'life',
 'watch',
 'old',
 'car',
 'killed',
 'train',
 'think',
 '4',
 'last',
 'ûªs',
 'accident',
 'let',
 'good',
 'make',
 'say',
 'gt',
 '2015',
 'w',
 'could',
 'way',
 'may',
 'many',
 'families',
 'need',
 'even',
 'years',
 'best',
 'mass',
 'bombing',
 'collapse',
 'right',
 'home',
 'water',
 'forest',
 'death',
 'army',
 'work',
 'black',
 'another',
 'really',
 'please',
 'lol',
 'wildfire',
 'never',
 'hot',
 'god',
 'read',
 'mh370',
 'look',
 'help',
 'bomber',
 'fatal',
 'live',
 'northern',
 'obama',
 '8',
 'pm',
 'japan',
 '11',
 'school',
 'much',
 'feel',
 'city',
 'wild',
 'flood',
 'reddit',
 'great',
 '9',
 'stop',
 'near',
 'night',
 'shit',
 'said',
 'latest',
 'injured',
 '6',
 'typhoon',
 'top',
 'homes',
 'services',
 'floods',
 'hope',
 'fear',
 'ever',
 'legionnaires',
 'atomic',
 'house',
 'flames',
 '10',
 'truck',
 'state',
 'post',
 'getting',
 '15',
 'wreck',
 'ass',
 'everyone',
 'every',
 'damage',
 'content',
 'change',
 'red',
 'earthquake',
 'cross',
 'summer',
 'since',
 'severe',
 'plan',
 'oil',
 'coming',
 '7',
 'weather',
 'military',
 'found',
 'food',
 'ûò',
 'thunderstorm',
 'heat',
 'family',
 'debris',
 'without',
 'next',
 'little',
 'wounded',
 'natural',
 'lightning',
 'hit',
 'gonna',
 'evacuation',
 'devastated',
 'cause',
 'always',
 'well',
 'smoke',
 'set',
 'times',
 'survive',
 'national',
 'looks',
 'free',
 'destroyed',
 'boy',
 'terrorist',
 'story',
 'photo',
 'murder',
 'malaysia',
 'injuries',
 'check',
 'bloody',
 'bad',
 'trapped',
 'spill',
 'someone',
 'service',
 'says',
 'run',
 'refugees',
 'liked',
 'fucking',
 'flooding',
 'failure',
 '70',
 'women',
 'tonight',
 'show',
 'oh',
 'loud',
 'fall',
 'china',
 'area',
 '30',
 '08',
 'ûª',
 'thunder',
 'saudi',
 'rain',
 'movie',
 'landslide',
 'game',
 'boat',
 'around',
 'week',
 'weapon',
 'terrorism',
 'rescue',
 'p',
 'girl',
 'confirmed',
 'call',
 'blood',
 'bag',
 'air',
 'wind',
 'survived',
 'put',
 'migrants',
 'injury',
 'head',
 'hail',
 'drought',
 'weapons',
 'survivors',
 'screaming',
 'report',
 'released',
 'panic',
 'kills',
 'hurricane',
 'hostage',
 'explosion',
 'destroy',
 'burned',
 'big',
 'whole',
 'warning',
 'save',
 'rescued',
 'missing',
 'hazard',
 'breaking',
 'attacked',
 'thing',
 'past',
 'mosque',
 'made',
 'heard',
 'fuck',
 'destruction',
 'bridge',
 'apocalypse',
 '40',
 'violent',
 'trauma',
 'sinking',
 'sinkhole',
 'responders',
 'rescuers',
 'ok',
 'hundreds',
 'high',
 'drowning',
 'bags',
 'wave',
 'self',
 'saw',
 'real',
 'massacre',
 'keep',
 'island',
 'dust',
 'demolished',
 'deaths',
 'crush',
 'crashed',
 'collapsed',
 'catastrophic',
 '0',
 'white',
 'use',
 'stock',
 'river',
 'lives',
 'lava',
 'hazardous',
 'explode',
 'evacuate',
 'due',
 'county',
 'blown',
 'wreckage',
 'update',
 'trouble',
 'traumatised',
 'tragedy',
 'structural',
 'screamed',
 'quarantine',
 'outbreak',
 'must',
 'market',
 'long',
 'light',
 'exploded',
 'drown',
 'displaced',
 'derailment',
 'collision',
 'collided',
 'charged',
 'catastrophe',
 'bang',
 'away',
 'august',
 'ambulance',
 'screams',
 'ruin',
 'quarantined',
 'meltdown',
 'least',
 'group',
 'electrocuted',
 'crushed',
 'calgary',
 'bombed',
 'blew',
 'bleeding',
 'battle',
 '05',
 '00',
 'wounds',
 'three',
 'suspect',
 'riot',
 'part',
 'panicking',
 'obliteration',
 'mudslide',
 'investigators',
 'inundated',
 'harm',
 'flattened',
 'engulfed',
 'deluged',
 'curfew',
 'caused',
 'blast',
 'better',
 'bagging',
 'b',
 'arson',
 'anniversary',
 'airplane',
 'wrecked',
 'windstorm',
 'twister',
 'thought',
 'something',
 'sirens',
 'seismic',
 'sandstorm',
 'rioting',
 'obliterated',
 'obliterate',
 'horrible',
 'hijacking',
 'half',
 'devastation',
 'detonation',
 'desolation',
 'danger',
 'cliff',
 'casualties',
 'bus',
 'baby',
 'woman',
 'went',
 'twitter',
 'sure',
 'sunk',
 'snowstorm',
 'send',
 'security',
 'road',
 'power',
 'minute',
 'iran',
 'hostages',
 'derailed',
 'derail',
 'demolish',
 'cyclone',
 'collide',
 'chemical',
 'bioterrorism',
 'whirlwind',
 'things',
 'pkk',
 'phone',
 'murderer',
 'line',
 'hijacker',
 'heart',
 'fedex',
 'famine',
 'died',
 'zone',
 'volcano',
 'ur',
 'tomorrow',
 'song',
 'rubble',
 'pandemonium',
 'longer',
 'eyewitness',
 'detonated',
 'detonate',
 'demolition',
 'came',
 'blazing',
 'airport',
 'ûó',
 'tsunami',
 'trying',
 'stretcher',
 'south',
 'sound',
 'razed',
 'kids',
 'hijack',
 'gets',
 'fatalities',
 'fan',
 'evacuated',
 'electrocute',
 'ebay',
 'avalanche',
 'armageddon',
 'annihilated',
 'affected',
 'ûªt',
 'yet',
 'turkey',
 'soon',
 'remember',
 'rainstorm',
 'kill',
 'government',
 'goes',
 'fatality',
 'drowned',
 'deluge',
 'casualty',
 'building',
 'america',
 'west',
 'used',
 'tornado',
 'shoulder',
 'shooting',
 'land',
 'isis',
 'fight',
 'far',
 'blight',
 'bioterror']

In [22]:
def bagofwords(sentence, words):
    sentence_words = extract_words(sentence) 
    bag = np.zeros(len(words)) 
    for sw in sentence_words:
        for i,word in enumerate(words):
            if word == sw:
                bag[i] += 1
    return np.array(bag)

In [23]:
n_words = len(vocab)
n_docs = len(df)
bag_o = np.zeros([n_docs,n_words])
for ii in range(n_docs):
    bag_o[ii,:] = bagofwords(df['text'].iloc[ii], vocab)
    bag_o.shape

In [26]:
sorted(ash_map.items(), key=lambda item: item[1], reverse=True)[:20]

[('co', 6800),
 ('http', 6154),
 ('https', 618),
 ('û_', 514),
 ('amp', 510),
 ('like', 492),
 ('fire', 365),
 ('get', 336),
 ('new', 329),
 ('via', 325),
 ('2', 310),
 ('news', 288),
 ('people', 283),
 ('emergency', 229),
 ('video', 227),
 ('disaster', 220),
 ('would', 214),
 ('3', 202),
 ('police', 199),
 ('still', 180)]

In [28]:
numdocs, numwords = np.shape(bag_o)
#Переход к формуле tfidf, как указано выше
N = numdocs
word_frequency = np.empty(numwords)
#Подсчет количества документов, в которых появляется слово
for word in range(numwords):
    word_frequency[word]=np.sum((bag_o[:,word]>0))
    idf = np.log(N/word_frequency)
    idf.shape
    idf

<ipython-input-28-f9693fbd38c8>:8: RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log(N/word_frequency)

In [29]:
tfidf = np.empty([numdocs, numwords])
for doc in range(numdocs):
    tfidf[doc, :]=bag_o[doc, :]*idf
    tfidf.shape

In [30]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import GridSearchCV

In [31]:
X_train, X_test, y_train, y_test = train_test_split(tfidf,df['relevance'].values,shuffle=True)
N_train, _ = X_train.shape
N_test, _ = X_test.shape
print(N_train, N_test)

8145 2715

In [32]:
print (tfidf)
print (df['relevance'])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.64339282 0.74842242 0.         ... 0.         0.         0.        ]
 [0.64339282 0.74842242 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
0        1
1        1
2        1
3        1
4        1
        ..
10871    1
10872    1
10873    1
10874    1
10875    1
Name: relevance, Length: 10860, dtype: int64

In [33]:
print(X_train.shape, X_test.shape)

(8145, 500) (2715, 500)

In [34]:
print(X_train.shape, X_test.shape)

(8145, 500) (2715, 500)

In [35]:
model = SVC()
model.fit(X_train,y_train)

SVC()

In [36]:
y_pred = model.predict(X_test) # предсказать значение целевой переменной
print(y_pred)

[0 0 0 ... 1 1 0]

In [37]:
score = model.score(X_test, y_test)
print(score)

0.8022099447513812

In [38]:
print('Точность классификатора логистической регрессии на тестовом наборе: {:.3f}'.format
(score))

Точность классификатора логистической регрессии на тестовом наборе: 0.802

In [39]:
score = model.score(X_train,y_train)
print(score)

0.881767955801105

In [41]:
print('Точность классификатора логистической регрессии на обучающем наборе: {:.3f}'.format(score))

Точность классификатора логистической регрессии на обучающем наборе: 0.882